[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[[redirects]]
  from = "/annotations"
  to = "/.netlify/functions/annotations"
  status = 200

[[redirects]]
  from = "/data"
  to = "/.netlify/functions/data"
  status = 200

[[redirects]]
  from = "/export"
  to = "/.netlify/functions/export"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
